# Generated by Django 2.2 on 2021-05-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
