# Generated by Django 2.2 on 2021-05-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress_app', '0002_auto_20210511_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOfCongress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('cid', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
                ('party', models.CharField(max_length=10)),
                ('chamber', models.CharField(max_length=5)),
                ('first_elected', models.IntegerField()),
                ('total_contributions', models.FloatField()),
            ],
        ),
    ]
