# Generated by Django 2.2 on 2021-05-12 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congress_app', '0003_memberofcongress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating', models.IntegerField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='congress_app.MemberOfCongress')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='congress_app.User')),
            ],
        ),
    ]
